services:
  database:
    container_name: zabbix-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: zabbix-server
    build:
      context: ./zabbix-server
      dockerfile: Dockerfile
    environment:
      DB_SERVER_HOST: database
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    depends_on:
      - database
    ports:
      - "10051:10051"
    restart: unless-stopped

  frontend:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: database
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: backend
      PHP_TZ: Europe/Moscow
    ports:
      - "8080:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: zabbix-grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped

volumes:
  database:
  grafana:
