services:
  nginx:
    container_name: reverse-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - storage:/etc/nginx/conf.d
    restart: unless-stopped

volumes:
  storage:
