services:
  backend:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_storage:/data
    networks:
      - proxy
    environment:
      TZ: "Europe/Moscow"

volumes:
  portainer_storage:

networks:
  proxy:
    external: true
